[package]
name = "my-money"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", feaures = ["serde"] }
clap = { version = "4.5.4", features = ["derive", "cargo"] }
serde = { version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
prettytable-rs = "^0.10"